server:
  port: 8085

spring:
  application:
    name: notification-service



  mail:
   host: smtp.gmail.com
   port: 465          # Change 587 to 465
   username: your email
   password: App password
   properties:
     mail:
       debug: true    # Keep debug on to see logs
       smtp:
          auth: true
          ssl:
           enable: true        # Use SSL instead of STARTTLS
           trust: "*"          # Trust the server certificate
           # Remove or set starttls.enable to false
       starttls:
           enable: false