server:
  port: 8085 # Port for the NotificationService

spring:
  application:
    name: notification-service



  # --- Email SMTP Configuration (from architecture doc) ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail # <-- REPLACE THIS
    password: your email password     # <-- REPLACE THIS
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true